import { readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PermissionFlagsBits, ChannelType } from 'discord.js';
import JSZip from 'jszip';
import {
  PACK_NAME, PACK_DESCRIPTION, PACK_AUTHOR, MAINTAINER_ROLE, BASE_TIERS,
  HEADER_UUID, MODULE_UUID, MIN_ENGINE_VERSION, DEPENDENCIES,
  FORUM_NAME_HINT, PINNED_POST_TITLE,
} from '../config/raritystats.js';
import { rrsGetMeta, rrsSetForumThread } from './db.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ASSET_DIR = join(__dirname, '..', 'assets');

export function isAddonMaintainer(member) {
  return member.permissions.has(PermissionFlagsBits.Administrator)
    || member.roles.cache.some((r) => r.name === MAINTAINER_ROLE);
}

// --- Validation --------------------------------------------------------------
// Returns { value } on success or { error } with a human message. Custom/namespaced
// rarity tiers are allowed (only warned about, never rejected).
export function validateMaterial(obj) {
  if (!obj || typeof obj !== 'object') return { error: 'Material must be a JSON object.' };
  if (!obj.material || typeof obj.material !== 'string') return { error: '`material` must be a non-empty string.' };
  if (!obj.rarityWeightMods || typeof obj.rarityWeightMods !== 'object') return { error: '`rarityWeightMods` must be an object of tier → multiplier.' };
  for (const [tier, mult] of Object.entries(obj.rarityWeightMods)) {
    if (typeof mult !== 'number') return { error: `rarityWeightMods.${tier} must be a number.` };
  }
  const mr = obj.maxRarity;
  if (mr === undefined || (typeof mr !== 'number' && typeof mr !== 'string')) return { error: '`maxRarity` must be a rank number or a tier slug.' };
  const warnings = Object.keys(obj.rarityWeightMods).filter((t) => !BASE_TIERS.includes(t));
  return { value: obj, warnings: warnings.length ? `Non-base tiers referenced: ${warnings.join(', ')}` : null };
}

export function validateItemType({ type, match }) {
  if (!type || typeof type !== 'string') return { error: '`type` (group name) must be a non-empty string.' };
  if (!Array.isArray(match) || !match.length || match.some((m) => !m || typeof m !== 'string')) {
    return { error: '`match` must be a non-empty list of substrings.' };
  }
  return { value: { type, match } };
}

// --- Pack generation ---------------------------------------------------------
async function resolveApiScript() {
  const url = process.env.RRS_API_URL;
  if (url) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(8000) });
      if (res.ok) return await res.text();
      console.warn(`[rrs] RRS_API_URL returned ${res.status}; using bundled API.`);
    } catch (e) {
      console.warn(`[rrs] RRS_API_URL fetch failed (${e.message}); using bundled API.`);
    }
  }
  return readFileSync(join(ASSET_DIR, 'rarityStatsAPI.js'), 'utf8');
}

function manifest(version) {
  return {
    format_version: 2,
    metadata: { authors: [PACK_AUTHOR], product_type: 'addon' },
    header: { name: PACK_NAME, description: PACK_DESCRIPTION, uuid: HEADER_UUID, version, min_engine_version: MIN_ENGINE_VERSION },
    modules: [{ type: 'script', language: 'javascript', entry: 'scripts/main.js', uuid: MODULE_UUID, version }],
    dependencies: DEPENDENCIES,
  };
}

function buildMainJs(materials, itemTypes) {
  return `import { system } from '@minecraft/server';
import * as rrs from './rarityStatsAPI.js';

// Generated by the Discord bot — do not edit by hand.
const MATERIALS = ${JSON.stringify(materials, null, 2)};
const ITEM_TYPES = ${JSON.stringify(itemTypes, null, 2)};

system.run(async () => {
  const ok = await rrs.ping();
  if (!ok) { console.warn('[R&S Support] Rarity & Stats not detected — nothing registered.'); return; }
  for (const m of MATERIALS) rrs.registerMaterial(m);
  for (const t of ITEM_TYPES) rrs.registerItemType(t.type, t.match);
  console.warn('[R&S Support] registered ' + MATERIALS.length + ' material(s), ' + ITEM_TYPES.length + ' item type(s).');
});
`;
}

// Build the .mcaddon (a zip) in memory. Returns a Buffer.
export async function buildPackBuffer(materials, itemTypes, version) {
  const zip = new JSZip();
  zip.file('manifest.json', JSON.stringify(manifest(version), null, 2));
  zip.file('scripts/rarityStatsAPI.js', await resolveApiScript());
  zip.file('scripts/main.js', buildMainJs(materials, itemTypes));
  const iconPath = join(ASSET_DIR, 'pack_icon.png');
  if (existsSync(iconPath)) zip.file('pack_icon.png', readFileSync(iconPath));
  return zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
}

// --- Forum target ------------------------------------------------------------
async function resolveForum(guild) {
  const id = process.env.RRS_FORUM_CHANNEL_ID;
  if (id) {
    const c = await guild.channels.fetch(id).catch(() => null);
    if (c?.type === ChannelType.GuildForum) return c;
  }
  return guild.channels.cache.find(
    (c) => c.type === ChannelType.GuildForum && c.name.toLowerCase().includes(FORUM_NAME_HINT),
  ) ?? null;
}

// Get (or create + pin) the support-pack post. Returns { thread } or { error }.
export async function resolveForumThread(guild) {
  const meta = await rrsGetMeta(guild.id);
  if (meta?.forum_thread_id) {
    const t = await guild.channels.fetch(meta.forum_thread_id).catch(() => null);
    if (t) return { thread: t };
  }
  const forum = await resolveForum(guild);
  if (!forum) {
    return { error: 'No Rarity & Stats forum found. Set `RRS_FORUM_CHANNEL_ID`, or create a forum whose name includes "rarity", then run `/rrs setforum`.' };
  }
  let thread;
  try {
    thread = await forum.threads.create({
      name: PINNED_POST_TITLE,
      message: { content: 'Latest **Rarity & Stats — Support Pack** builds are posted here. Load it alongside Rarity & Stats.' },
    });
  } catch (e) {
    return { error: `Could not create the forum post: ${e.message}` };
  }
  await thread.pin('R&S support pack post').catch(() => {});
  await rrsSetForumThread(guild.id, thread.id);
  return { thread };
}
